### ISSUE TITLE
PVRTexTool can't recognize the EncodeToTGA texture file.

### ISSUE THREAD

**Issue by floydchenv** [phwitti/EncodeToTGA#1]

**Comment by floydchenv** [comment]
UnityVersion: Unity 2017.4.1f

**Comment by phwitti** [comment]
This Bug should actually have been filed to PVRTexTool -- as they only provide support for one certain type of TGA-File. No Run-Length-Encoding and File 'has' to end with optional-tga-footer that was added in version 2 of the file specifications.

Still, as I want this script to provide an easy don't-have-to-think-about anything encoder that works in most cases i added support for uncompressed files (just pass Compression.None for the optional parameter), and also add the optional footer (as this does no harm -- before version 2 the file could just end in whatever one felt to put in there).
